import os
import json
import smtplib
from pathlib import Path
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

# ============================
# CONFIGURATION & PATHS
# ============================
PROJECT_ROOT = Path(__file__).resolve().parent
JSON_INPUT = PROJECT_ROOT / "docs" / "data" / "daily_brief.json"

EMAIL_USER = os.getenv("EMAIL_USER")
EMAIL_PASS = os.getenv("EMAIL_PASS")
EMAIL_TO = os.getenv("EMAIL_TO")

# ============================
# HTML GENERATOR
# ============================
def build_html_body(data):
    date_str = data.get("date", datetime.now().strftime("%B %d, %Y"))
    stories = data.get("top_stories", [])
    microsite_url = "https://Apoorva840.github.io/ai-executive-brief/"
    
    html = f"""
    <html>
    <body style="font-family: 'Segoe UI', Arial, sans-serif; color: #333; line-height: 1.6; max-width: 600px; margin: auto; padding: 20px;">
        <h2 style="color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; margin-bottom: 0;">
            Daily AI Executive Brief
        </h2>
        <p style="color: #7f8c8d; font-size: 0.9em; margin-top: 5px;">{date_str} | <a href="{microsite_url}" style="color: #3498db; text-decoration: none;">View Archive Online</a></p>
    """
    
    for item in stories:
        # 1. Handle Audience Tags
        audience_tags = ""
        if item.get("who_should_care"):
            roles = ", ".join(item["who_should_care"])
            audience_tags = f"<p style='font-size: 0.85em; color: #8e44ad;'><strong>Relevant for:</strong> {roles}</p>"

        # 2. Summary Recovery (Ensure text is NEVER blank)
        summary_display = item.get('summary')
        if not summary_display or len(summary_display.strip()) < 5:
            summary_display = "Review the technical source for full details on this update."

        html += f"""
        <div style="margin-bottom: 35px; padding: 20px; border-radius: 8px; border: 1px solid #eee; background: #ffffff; box-shadow: 0 2px 4px rgba(0,0,0,0.05);">
            <h3 style="margin-top: 0; color: #2980b9; font-size: 1.2em;">{item.get('rank', '•')}. {item['title']}</h3>
            <p style="font-size: 0.95em;">{summary_display}</p>
            <hr style="border: 0; border-top: 1px solid #eee; margin: 15px 0;">
            <p style="font-size: 0.9em;"><strong>Technical Takeaway:</strong> {item.get('technical_takeaway', 'See archive for analysis.')}</p>
            <p style="color: #c0392b; font-size: 0.9em;"><strong>Primary Risk:</strong> {item.get('primary_risk', 'Standard risks apply.')}</p>
            <p style="color: #27ae60; font-size: 0.9em;"><strong>Opportunity:</strong> {item.get('primary_opportunity', 'Incremental adoption gains.')}</p>
            {audience_tags}
            <p style="margin-top: 15px;"><a href="{item['url']}" style="background-color: #3498db; color: white; padding: 8px 15px; text-decoration: none; border-radius: 4px; font-size: 0.85em; display: inline-block;">Read Source ({item.get('source', 'Link')}) &rarr;</a></p>
        </div>
        """
    
    html += f"""
        <div style="margin-top: 40px; padding: 20px; text-align: center; background-color: #f8f9fa; border-radius: 8px;">
            <p style="margin-bottom: 15px; font-weight: bold; color: #2c3e50;">Access more insights online</p>
            <a href="{microsite_url}" style="background-color: #2c3e50; color: white; padding: 12px 25px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block;">
                Full Web Archive
            </a>
            <p style="margin-top: 25px; font-size: 0.75em; color: #95a5a6; border-top: 1px solid #ddd; padding-top: 15px;">
                Generated by Gemini AI Pipeline<br>
                © 2026 AI Executive Brief
            </p>
        </div>
    </body>
    </html>
    """
    return html

def send_email():
    if not EMAIL_USER or not EMAIL_PASS or not EMAIL_TO:
        print(" ERROR: Missing EMAIL environment variables.")
        return

    if not JSON_INPUT.exists():
        print(f" ERROR: {JSON_INPUT} not found.")
        return

    with open(JSON_INPUT, "r", encoding="utf-8") as f:
        brief_data = json.load(f)

    recipients = [e.strip() for e in EMAIL_TO.split(",")]
    subject = f"AI Executive Brief: {len(brief_data.get('top_stories', []))} stories for {brief_data.get('date')}"
    html_content = build_html_body(brief_data)

    msg = MIMEMultipart("alternative")
    msg["From"] = f"AI Briefing <{EMAIL_USER}>"
    msg["To"] = ", ".join(recipients)
    msg["Subject"] = subject
    msg.attach(MIMEText(html_content, "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(EMAIL_USER, EMAIL_PASS)
            server.send_message(msg, to_addrs=recipients)
        print(f"📧 Success: Email sent to {len(recipients)} recipients.")
    except Exception as e:
        print(f" Failed to send email: {e}")

if __name__ == "__main__":
    send_email()